Cities/Cities/Models/City.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Cities.Models
{
    public class City
    {
        [Display(Name = "City")]
        public string Name { get; set; }

        public string Country { get; set; }

        [DisplayFormat(DataFormatString = "{0:F2}", ApplyFormatInEditMode = true)]
        public int? Population { get; set; }

        public string Notes { get; set; }
    }
}

Cities/Cities/Models/CountryNames.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Cities.Models
{
    public enum CountryNames
    {
        UK,
        USA,
        France,
        China
    }
}

Cities/Cities/Models/Repository.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Cities.Models
{
    public interface IRepository
    {
        IEnumerable<City> Cities { get; }
        void AddCity(City newCity);
    }

    public class MemoryRepository : IRepository
    {
        private List<City> cities = new List<City>
        {
            new City { Name = "London", Country = "UK", Population = 8539000},
            new City { Name = "New York", Country = "USA", Population = 8406000 },
            new City { Name = "San Jose", Country = "USA", Population = 998537 },
            new City { Name = "Paris", Country = "France", Population = 2244000 }
        };

        public IEnumerable<City> Cities => cities;

        public void AddCity(City newCity) => cities.Add(newCity);
    }
}

Cities/Cities/Components/TimeViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Cities.Components
{
    public class TimeViewComponent : ViewComponent
    {
        public IViewComponentResult Invoke() => View(DateTime.Now);
    }
}

Cities/Cities/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Cities.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace Cities.Controllers
{
    public class HomeController : Controller
    {
        private IRepository repository;

        public HomeController(IRepository repo) => repository = repo;

        public IActionResult Index() => View(repository.Cities);

        public IActionResult Edit()
        {
            ViewBag.Countries = new SelectList(repository.Cities.Select(c => c.Country).Distinct());
            return View("Create", repository.Cities.First());
        }

        public IActionResult Create()
        {
            ViewBag.Countries = new SelectList(repository.Cities.Select(c => c.Country).Distinct());
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(City city)
        {
            repository.AddCity(city);
            return RedirectToAction("Index");
        }
    }
}

Cities/Cities/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Cities</title>
    @*<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
        <script src="https://code.jquery.com/jquery-3.3.1.min.js"> </script>*@
    @*<script asp-src-include="/lib/jquery/dist/**/*.js"></script>*@
    @*<script asp-src-include="/lib/jquery/dist/**/*.min.js"></script>*@
    @*<script asp-src-include="/lib/jquery/dist/**/*.slim.min.js"></script>*@
    @*<script asp-src-include="/lib/jquery/dist/**/*.min.js"
                asp-src-exclude="**.slim.**">
        </script>*@
    @*<environment names="development">
            <script asp-src-include="/lib/jquery/dist/**/j*.js"
                    asp-src-exclude="**.slim.**,**.min.**">
            </script>
        </environment>
        <environment names="staging, production">
            <script asp-src-include="/lib/jquery/dist/**/*.min.js"
                    asp-src-exclude="**.slim.**">
            </script>
        </environment>*@
    @*<script src="http://ajax.aspnetcdn.com/ajax/jQuery/jquery-3.2.1.min.js"></script>*@
    @*<script src="http://ajax.aspnetcdn.com/ajax/jQuery/jquery-3.2.1.min.js"
                asp-fallback-src-include="/lib/jquery/dist/**/*.min.js"
                asp-fallback-src-exclude="**.slim.**"
                asp-fallback-test="window.jQuery">
        </script>*@
    @*<link href="/lib/bootstrap/dist/css/bootstrap.css" rel="stylesheet" />*@
    @*<link rel="stylesheet"
        asp-href-include="/lib/bootstrap/dist/**/*.min.css"
        asp-href-exclude="**/*-reboot*,**/*-grid*" />*@
    @*<link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css"
        asp-fallback-href-include="/lib/bootstrap/dist/**/*.min.css"
        asp-fallback-href-exclude="**/*-reboot*,**/*-grid*"
        asp-fallback-test-class="btn"
        asp-fallback-test-property="display"
        asp-fallback-test-value="inline-block"
        rel="stylesheet" />*@
    <link href="~/lib/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet" />

</head>
<body class="m-1 p-1">
    @*<environment names="development">
            <div class="m-1 p-1 bg-info"><h2>This is Development</h2></div>
        </environment>
        <environment names="production">
            <div class="m-1 p-1 bg-danger"><h2>This is Production</h2></div>
        </environment>*@
    @*<img src="/images/city.jpg" asp-append-version="true" />*@
    <div>@RenderBody()</div>
    <cache expires-after="@TimeSpan.FromSeconds(15)">
        @await Component.InvokeAsync("Time")
    </cache>
</body>
</html>