UsingViewComponents/UsingViewComponents/Models/City.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace UsingViewComponents.Models
{
    public class City
    {
        public string Name { get; set; }

        public string Country { get; set; }

        public int Population { get; set; }
    }
}

UsingViewComponents/UsingViewComponents/Models/CityRepository.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace UsingViewComponents.Models
{
    public interface ICityRepository
    {
        IEnumerable<City> Cities { get; }
        void AddCity(City newCity);
    }

    public class MemoryCityRepository : ICityRepository
    {
        private List<City> cities = new List<City>
        {
            new City { Name = "London", Country = "UK", Population = 8539000},
            new City { Name = "New York", Country = "USA", Population = 8406000 },
            new City { Name = "San Jose", Country = "USA", Population = 998537 },
            new City { Name = "Paris", Country = "France", Population = 2244000 }
        };

        public IEnumerable<City> Cities => cities;

        public void AddCity(City newCity) => cities.Add(newCity);
    }
}

UsingViewComponents/UsingViewComponents/Models/CityViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace UsingViewComponents.Models
{
    public class CityViewModel
    {
        public int Cities { get; set; }

        public int Population { get; set; }
    }
}

UsingViewComponents/UsingViewComponents/Models/Product.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace UsingViewComponents.Models
{
    public class Product
    {
        public string Name { get; set; }

        public decimal Price { get; set; }
    }
}

UsingViewComponents/UsingViewComponents/Models/ProductRepository.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace UsingViewComponents.Models
{
    public interface IProductRepository
    {
        IEnumerable<Product> Products { get; }
        void AddProduct(Product newProduct);
    }

    public class MemoryProductRepository : IProductRepository
    {
        private List<Product> products = new List<Product>
        {
            new Product { Name = "Kayak", Price = 275M },
            new Product { Name = "Lifejacket", Price = 48.95M },
            new Product { Name = "Soccer ball", Price = 19.50M }
        };

        public IEnumerable<Product> Products => products;

        public void AddProduct(Product newProduct) => products.Add(newProduct);
    }
}

UsingViewComponents/UsingViewComponents/Components/PocoViewComponent.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using UsingViewComponents.Models;

namespace UsingViewComponents.Components
{
    public class PocoViewComponent
    {
        private ICityRepository repository;

        public PocoViewComponent(ICityRepository repo) => repository = repo;

        public string Invoke() => 
            $"{repository.Cities.Count()} cities, " +
            $"{repository.Cities.Sum(c => c.Population)} people";
    }
}

UsingViewComponents/UsingViewComponents/Controllers/CityController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ViewComponents;
using Microsoft.AspNetCore.Mvc.ViewFeatures;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using UsingViewComponents.Models;

namespace UsingViewComponents.Controllers
{
    [ViewComponent(Name = "ComboComponent")]
    public class CityController : Controller
    {
        private ICityRepository repository;

        public CityController(ICityRepository repo) => repository = repo;

        public ViewResult Create() => View();

        [HttpPost]
        public IActionResult Create(City newCity)
        {
            repository.AddCity(newCity);
            return RedirectToAction("Index", "Home");
        }

        public IViewComponentResult Invoke() =>
            new ViewViewComponentResult()
            {
                ViewData = new ViewDataDictionary<IEnumerable<City>>(ViewData, repository.Cities)
            };
    }
}

UsingViewComponents/UsingViewComponents/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using UsingViewComponents.Models;

namespace UsingViewComponents.Controllers
{
    public class HomeController: Controller
    {
        private IProductRepository repository;

        public HomeController(IProductRepository repo) => repository = repo;

        public ViewResult Index() => View(repository.Products);

        public ViewResult Create() => View();

        [HttpPost]
        public IActionResult Create(Product newProduct)
        {
            repository.AddProduct(newProduct);
            return RedirectToAction("Index");
        }
    }
}

UsingViewComponents/UsingViewComponents/Views/Home/Create.cshtml
@model UsingViewComponents.Models.Product
@{
    ViewData["Title"] = "Create Product";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<form method="post" asp-action="Create">
    <div class="form-group">
        <label asp-for="Name">Name:</label>
        <input class="form-control" asp-for="Name" />
    </div>
    <div class="form-group">
        <label asp-for="Price">Price:</label>
        <input class="form-control" asp-for="Price" />
    </div>

    <button type="submit" class="btn btn-primary">Create</button>

    <a class="btn btn-secondary" asp-action="Index">Cancel</a>
</form>

UsingViewComponents/UsingViewComponents/Views/Home/Index.cshtml
@model IEnumerable<UsingViewComponents.Models.Product>
@{
    ViewData["Title"] = "Products";
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewBag.Ololo = "Hello";
}

<table class="table table-sm table-striped table-bordered">
    <thead>
        <tr><th>Name</th><th>Price</th></tr>
    </thead>
    <tbody>
        @foreach (var product in Model)
        {
            <tr>
                <td>@product.Name</td>
                <td>@product.Price</td>
            </tr>
        }
    </tbody>
</table>

<a asp-action="Create" class="btn btn-primary">Create</a>

UsingViewComponents/UsingViewComponents/Views/Shared/Components/ComboComponent/Default.cshtml
@model IEnumerable<UsingViewComponents.Models.City>

<table class="table table-sm table-bordered">
    <tr>
        <td>Biggest City:</td>
        <td>
            @Model.OrderByDescending(c => c.Population).First().Name
        </td>
    </tr>
</table>
<a class="btn btn-sm btn-info" asp-controller="City" asp-action="Create">
    Create City    
</a>